server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://database:5432/gestion_des_stages
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:hels}
    password: ${DB_PASSWORD:hels}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  upload-dir: /app/uploads
  images-dir: /app/uploads/images
  documents-dir: /app/uploads/documents
  profiles-dir: /app/uploads/profiles

jwt:
  secret:
    key: ${JWT_SECRET:F06PBJ6GzaTRCyiAycvwVHn0Mkgi9ztGpl6DIkULwtDcJ2y17uDwYS0XdrNjIIfWKAvWPoyAwBLHvHKnDzzPmmXWEpaRbWVG8zGkIViUWumw64U6nGOE2d5a7Zb9sQaOrmYfxCHTbPinjbSOoMuSJhk793ewS3COygGtNoAKjGZgiwzlWpIgAYDxTDHzJAL6gp8YEuxmq5CpovVtTm6V4hvEf3kA7zBmjWctjTULcXlQ2VjfhH6WI48lJ5gqBZWl}
  expiration: 86400000

logging:
  level:
    com.groupe.gestionDesStages: INFO
    org.springframework.security: INFO